cdalvaro/docker-salt-master

CHANGELOG.md, Dockerfile, assets/build/install.sh, hooks/build
`crond` has been added to the supervisor
Additionally, Docker labels have been changed to accomplish the [label-schema.org](http://label-schema.org/rc1/) standard.
=> Add crond to supervisor

.circleci/config.yml, assets/runtime/functions.sh
The '*' was not selecting the files inside `/home/salt/logs/salt`
Additionally, adds support for CircleCI continuous integration
=> Bugfix: logrotate was not selecting salt logs

.github/workflows/publish.yml
This prevents publishing to fail when a new architecture is added.
=> Allow failures when caching images

.github/workflows/build-and-test.yml, .github/workflows/publish.yml, README.md, docker-compose.yml
This PR add more documentation about how to configure the `salt-api` service.
@vskubriev, could you check if this new documentation is more complete? Or do you miss something?
Thank you in advance for your help!
Closes #40
=> doc: Update salt-api documentation

assets/runtime/functions.sh
If any files are mounted from k8s secrets the chown commands will fail
due to the fact that these files will only be read-only.
This commit ignores any errors during the chown commands.
=> Ignore chown errors

CHANGELOG.md, Dockerfile, assets/sbin/config-reloader, docker-compose.yml
Fix an issue restarting `salt-master` processes with `supervisorctl` when reloading config.
=> fix(reload-config): Kill all salt-master instances

.github/ISSUE_TEMPLATE/bug_report.md, CHANGELOG.md, Dockerfile, Makefile, README.md, assets/runtime/functions.sh
- Fix: check GPG env variables before exiting if `gpgkeys` directory is empty.
=> Check GPG env variables before exiting if gpgkeys directory is empty

.github/workflows/build-and-test.yml, CHANGELOG.md, Dockerfile, assets/sbin/healthcheck, tests/basic/README.md, tests/basic/test.sh, tests/config-reloader/README.md, tests/gitfs/README.md, tests/gpg/README.md, tests/healthcheck/README.md, tests/healthcheck/test.sh, tests/salt-api/README.md
Healthcheck was not working because the `salt-call` command was returning always exit code `0` instead of returning `1` when the check was failing.
Changes:
- Fix healthcheck script (84db110732cb9594fcb9ca06e591d317ca2bfb87)
=> Fix healthcheck

.github/ISSUE_TEMPLATE/bug_report.md, .github/workflows/build-and-test.yml, CHANGELOG.md, Dockerfile, README.md, assets/runtime/functions.sh, docs/es-ES/README.md, entrypoint.sh, tests/keys-mount-point/README.md, tests/keys-mount-point/test.sh
Fixes an issue with `salt-key` and the generation keys directory.
When the keys directory is mounted as a host volume and the host system is macOS, `salt-key` cannot properly create the private keys.
This PR addresses this issue by creating keys inside a temporary directory and then moving them into the destination directory.
This PR fixes #226
=> Fix a bug setting keys directory permissions

.github/ISSUE_TEMPLATE/bug_report.md, .github/workflows/build-and-test.yml, CHANGELOG.md, Dockerfile, README.md, assets/runtime/functions.sh, docs/es-ES/README.md, tests/python-extra-packages/README.md, tests/python-extra-packages/test.sh
This PR adds support for installing Python extra packages.
Two methods can be used:
- Defining `PYTHON_PACKAGES_FILE` pointing to a _requirements.txt_ inside the container.
- Defining `PYTHON_PACKAGES` env variable with a list of packages to install via pip.
This PR closes #234
=> feat: Add support for installing Python extra packages

CHANGELOG.md, assets/build/install.sh, assets/runtime/functions.sh
Although the service is run under `root` user, `salt-master` changes the process owner to `salt` once the service has started.
=> fix: Run `salt-master` and `salt-api` services as `root`

.github/ISSUE_TEMPLATE/bug_report.md, CHANGELOG.md, Dockerfile, README.md, assets/build/install.sh, assets/runtime/env-defaults.sh, assets/runtime/functions.sh, compose.yml, docs/es-ES/README.md, tests/basic/test.sh
- Revert default `salt`'s user `PUID` and `PGID` values to `1000`. Now the `ubuntu` user is deleted before `salt` user creation.
- Fixes an issue setting permissions for master keys under some platforms (Closes #245).
- Change Docker base image to `ubuntu:noble-20240530`.
=> Improve `salt` user permissions management

.github/ISSUE_TEMPLATE/bug_report.md, CHANGELOG.md, Dockerfile, README.md, docs/es-ES/README.md
In this PR, the creation of volumes within the Dockerfile is removed.
Therefore, volumes will no longer be created automatically. As a result, if the keys or logs directories are not mounted when the container starts, their content will be lost when the container is deleted.
This PR closes #264
=> feat: Do not create volumes within Dockerfile

.github/ISSUE_TEMPLATE/bug_report.md, CHANGELOG.md, Dockerfile, README.md, assets/build/install.sh, assets/runtime/env-defaults.sh, docs/es-ES/README.md, tests/lib/common.sh, tests/salt-api/test.sh
Although the docs say that creation of the salt-api user can be avoided by setting `SALT_API_USER=""` this doesn't currently work.
The code uses:
https://github.com/cdalvaro/docker-salt-master/blob/44c73c718b652b94b180c9214acdb9c8417e04b1/assets/runtime/env-defaults.sh#L11
However this doesn't distinguish between unset and null, so always sets `SALT_API_USER=salt_api`
This PR uses an alternative method of parameter expansion to test if `$SALT_API_USER` is undefined instead of null before setting a default value, resulting in:
```
> unset SALT_API_USER
> source runtime/env-defaults.sh
> echo $SALT_API_USER
salt_api
>
> SALT_API_USER=""
> source runtime/env-defaults.sh
> echo $SALT_API_USER
```
This then means that:
https://github.com/cdalvaro/docker-salt-master/blob/44c73c718b652b94b180c921 …
=> Misc updates for LDAP API authentication

.github/workflows/build-and-test.yml, README.md, assets/build/functions.sh, assets/build/install.sh, docs/es-ES/README.md
SaltProject packages have been migrated from repo.saltproject.io to packages.broadcom.com repository.
https://saltproject.io/blog/salt-project-package-repo-migration-and-guidance/
This PR closes #273
=> chore: Update salt installation repository

.github/workflows/build-and-test.yml, tests/salt-api/salt-api-ldap.sh
A first pass at adding salt-api ldap integration tests as promised.
The `osixia/openldap` container comes with 2 'builtin' users: `admin` and `readonly`, and we add an ldap group called `saltadmins` containing the `readonly` user.
We then set `salt-api.conf` to connect to the LDAP server, and set the `eauth` rules to give access 'directly' to the `admin` user and also to members of the `saltadmins` group.
We then get a token and run a command via the for both users, testing both eauth rules.
I have tweaked things to try to handle the start/stop of the openldap container and cleanup neatly - but you might prefer the existing `cleanup` function being extended to also shut down the openldap container, if found?
I also haven't added this test to the github workflow as I wasn't sure if it …
=> feat: Add salt-api ldap eauth tests.

.github/workflows/build-and-test.yml
This PR enables native runners for arm64 architecture.
More info at:
- [Actions: Arm-based linux and windows runners are now in public beta](https://github.blog/changelog/2024-06-03-actions-arm-based-linux-and-windows-runners-are-now-in-public-beta/)
- [Linux arm64 hosted runners now available for free in public repositories (Public Preview)](https://github.blog/changelog/2025-01-16-linux-arm64-hosted-runners-now-available-for-free-in-public-repositories-public-preview/)
=> test: Try arm64 runners

.github/workflows/build-and-test.yml, README.md, docs/es-ES/README.md, tests/gitfs/config/gitfs.conf
Update only the `gitfs_remotes` to use the format `git@github.com/USER/PROJECT.git`, keeping `ext_pillar` with a different format.
=> test: change GitFS repository format

Dockerfile
This change is intended to avoid quota limits from Docker hub
=> Use Ubuntu image from AWS Elastic Container Registry

.github/ISSUE_TEMPLATE/bug_report.md, .github/workflows/publish.yml, CHANGELOG.md, Dockerfile, README.md, assets/runtime/env-defaults.sh, assets/runtime/functions.sh, docs/es-ES/README.md
Added the environment variable `SALT_API_DISABLE_SSL` to disable SSL for the CherryPy server. Specially useful when running the server behind a reverse proxy.
=> Allow disabling salt-api SSL
